# Copyright 2025 D-Wave
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from collections.abc import Callable, Iterator

import numpy as np
from numpy.typing import NDArray


def bootstrap(
    array: NDArray,
    rng: np.random.Generator,
    repetitions: int = 200,
    bootstrap_function: Callable[[NDArray], float] = np.nanmedian,
    skipnan: bool = True,
) -> list[float]:
    """Estimate a statistic by bootstrap resampling.

    The input is flattened to one dimension before resampling. For each
    bootstrap sample, the statistic is computed by applying `bootstrap_function`
    to the resampled array.

    If `skipnan` is True, then NaN values are removed from the input before
    resampling. If all values are NaN, then the output is a list of NaN values.

    Args:
        array: The input data to resample.
        rng: A random number generator used for resampling.
        repetitions: The number of bootstrap samples to generate.
        bootstrap_function: A function that takes an array and returns a statistic.
        skipnan: Whether to ignore NaN values in the input.

    Returns:
        A list of bootstrap estimates of the statistic.
    """
    array = np.asarray(np.atleast_1d(array)).ravel()
    if skipnan:
        array = array[~np.isnan(array)]
        if len(array) == 0:
            return [np.nan] * repetitions

    output = []
    if len(array) > 0:
        for inds in generate_bootstrap_indices(array.size, repetitions, rng):
            output.append(bootstrap_function(array[inds]))

    return output


def generate_bootstrap_indices(
    size: int,
    repetitions: int,
    rng: np.random.Generator,
) -> Iterator[NDArray]:
    """Yield bootstrap index arrays of a given size and number of repetitions.

    Each index array is generated by sampling with replacement from the range of
    indices corresponding to the input size.

    Args:
        size: The size of the array for which to generate bootstrap indices.
        repetitions: The number of bootstrap index arrays to generate.
        rng: A random number generator used for sampling.

    Yields:
        An array of indices for a bootstrap sample.
    """
    for _ in range(repetitions):
        inds = rng.choice(range(size), replace=True, size=size)
        yield inds


def confidence_interval(array: NDArray, width: float = 0.95) -> tuple[float, float, float]:
    """Calculate a confidence interval for a statistic using quantiles.

    The input is flattened to one dimension before calculating quantiles. The
    confidence interval is calculated by taking the quantiles corresponding to
    the specified width.

    Args:
        array: The input data from which to calculate the confidence interval.
        width: The width of the confidence interval (e.g., 0.95 for a 95%
            confidence interval).

    Returns:
        A tuple of the form (median, lower_error, upper_error) where:
            - median is the median of the input array.
            - lower_error is the distance from the median to the lower bound of
                the confidence interval.
            - upper_error is the distance from the median to the upper bound of
                the confidence interval.
    """
    x = np.asarray(array).ravel()
    if len(x) == 0:
        return np.nan, np.nan, np.nan

    x.sort()
    low = x[int(np.floor((1 - width) / 2 * x.size))]
    high = x[int(np.floor((1 - (1 - width) / 2) * x.size))]
    med = np.median(x)

    return med, med - low, high - med
